In [1]:
#!pip install mp-api --upgrade
import numpy as np
from mp_api.client import MPRester
#from pymatgen.ext.matproj import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [2]:
mp_key = "zpmjFe6ZZzl6aqcqeGUTiXhaXzQXDSJl"
mp_id = "mp-961660"

In [3]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    el_bs = m.get_bandstructure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
    ph_bs = m.get_phonon_bandstructure_by_material_id(mp_id)
    ph_dos = m.get_phonon_dos_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [11]:
i_atom = [1,3,6]
i_symmop = [4,5,7]


# Première opération de symétrie

In [21]:

view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('select antimony; color lightsalmon')
view.script('select sodium; color gold')
view.script('select lithium; color palegreen')
view.script('draw SYMOP ' + str(i_symmop[0]) + ' {atomno = ' + str(i_atom[0]) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [22]:
symmop = symmops[i_symmop[0] - 1]
print(symmop)

Rot:
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


In [23]:
pos_init = conv_struc.sites[i_atom[0] -1].frac_coords
print(pos_init)

[0.5 0.  0. ]


In [24]:
pos_final = symmop.operate(pos_init)
print(pos_final)

[0.  0.5 0. ]


# Deuxième opération de symétrie


In [25]:

view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('select antimony; color lightsalmon')
view.script('select sodium; color gold')
view.script('select lithium; color palegreen')
view.script('draw SYMOP ' + str(i_symmop[1]) + ' {atomno = ' + str(i_atom[1]) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [26]:
symmop = symmops[i_symmop[1] - 1]
print(symmop)

Rot:
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


In [29]:
pos_init = conv_struc.sites[i_atom[1] -1].frac_coords
print(pos_init)

[0.  0.  0.5]


In [30]:
pos_final = symmop.operate(pos_init)
print(pos_final)

[ 0.   0.  -0.5]


# Deuxième opération de symétrie


In [31]:

view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('select antimony; color lightsalmon')
view.script('select sodium; color gold')
view.script('select lithium; color palegreen')
view.script('draw SYMOP ' + str(i_symmop[2]) + ' {atomno = ' + str(i_atom[2]) + '}')

JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [32]:
symmop = symmops[i_symmop[2] - 1]
print(symmop)

Rot:
[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]


In [33]:
pos_init = conv_struc.sites[i_atom[2] -1].frac_coords
print(pos_init)

[0.25 0.75 0.75]


In [34]:
pos_final = symmop.operate(pos_init)
print(pos_final)

[-0.25  0.75 -0.75]
